---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint tasks
driver:
  name: docker
platforms:
  - name: debian_10
    image: geerlingguy/docker-debian10-ansible
    pre_build_image: true
    container_default_behavior: no_defaults
provisioner:
  name: ansible
verifier:
  name: ansible
