name: Ansible Molecule
  #
# Run this workflow every time a new commit pushed to your repository
on:
  push:
  pull_request:
    branches: [master, main]

jobs:
  molecule:
    # Name the Job
    name: Ansible Molecule
    # Set the agent to run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ansible-version: ["2.10", "2.11"]

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Check out code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.2' # Python version in Debian/buster

      - uses: syphar/restore-virtualenv@v1 # run this instead make install + source venv/bin/activate
        id: cache-virtualenv
        with:
          requirement_files: requirements-${{ matrix.ansible-version }}.txt

      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - run: pip install pip setuptools wheel --upgrade
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - run: pip install -r requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - run: pip install -r requirements.txt --upgrade
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      # Check ansible version
      - run: ansible --version

      # Check molecule version
      - run: molecule --version

      # Create ansible.cfg with correct roles_path
      - run: printf '[defaults]\nroles_path=../' >ansible.cfg

      # Run molecule test
      - run: molecule test
